### PR TITLE
Comprehensive rewrite of Char tests

### PR DESCRIPTION
**Pull request by jonathanhefner**
Like #150, I rewrote the Char tests to be more comprehensive.  All exposed API functions are covered and tested with all alpha-decimal characters.  The tests are also more structured, so it is easier to add tests for future corner cases (e.g. `toLocaleLower` in a Turkish locale).

### CODE REVIEW

**Comment by jonathanhefner** [comment]
I'm... not sure what happened to the build.  Travis CI says the build timed out, but the tests run swiftly (and pass) locally.  Is it possibly a glitch in the build system?  Is there a way to trigger another attempt?

**Comment by jonathanhefner** [comment]
Looks like it was just a glitch.

In case anyone is curious, I was able to force another build by doing an empty `git commit --amend` and then a `git push -f` to my branch.

**Comment by evancz** [comment]
Why do you put single tokens in parentheses?

**Comment by jonathanhefner** [comment]
Just for consistency.  I guess it also feels a little easier to eyeball with the parens acting as delimiters, but that's subjective.

If it's bad practice (or just ugly), I can strip them out.

**Comment by evancz** [comment]
I'd generally consider it bad style to have extra parens, but I only care to the extent that people will use these tests as a guide for writing their own. I'm not sure what the right thing is here, but it feels weird.

In any case, things look good, thanks!

**Pull request merged**
