### PR TITLE
Task docs

### PR DESCRIPTION
**Pull request by rtfeldman**
This revises the `Task` docs to be more helpful to `elm-effects` users searching for how to obtain tasks that can never fail.

The resulting docs json file: [`task-docs.json`](https://gist.github.com/rtfeldman/ef89951043fafa67ad1b)

### CODE REVIEW

**Comment by vilterp** [comment]
Having a type variable `never` here and a type `Never` in `elm-effects` might be confusing. Maybe an argument for moving `Never` type to `core` and using it here?

**Comment by rgrempel** [comment]
I might be misunderstanding, but I believe the lower-case `never` is just documentation -- it essentially means that the error type is unconstrained -- since it never happens, the type system need not care about it. Whereas the upper-case `Never` is, technically, an actual type. So (and I may be missing something here) it seems like one would be over-constraining the type checker by making `Task.toMaybe` return a `Task Never (Maybe a)`. Whereas making it return a `Task never (Maybe a)` is just documentation.

**Comment by evancz** [comment]
Yeah, @rtfeldman and I discussed this. Richard, can you give more context on these things? Often when we discuss things offline, that info does not make it into the PR or issue and leads to confusion.

I'd be curious to see @vilterp's thoughts on the reasoning.

**Comment by rtfeldman** [comment]
Yep, sorry about that!

My understanding is that @rgrempel's [comment](https://github.com/elm-lang/core/pull/393#issuecomment-138017972) is correct as to what the distinction implies.

As for motivation, the reason I wanted to rename it was for searchability; if you are currently working with elm-effects and you think "okay, I need to get to a Never", you reflexively bring up the Task docs and search for "never" to see what comes back. Currently nothing comes back, so I have to hunt function by function until I find one whose docs indicate it'll do what I need.

Changing it to `Never` would be overly restrictive, but changing it to `never` makes it searchable. Granted, it could make people wonder "why is it capitalized in one place and not the other?" but that seems like the least painful of the options on the table.

**Pull request merged**
