### PR TITLE
Remove multi-way if usage, and use = for record updates.

### PR DESCRIPTION
**Pull request by laszlopandy**
@evancz 
@JoeyEremondi

### CODE REVIEW

**Comment by evancz** [comment]
Looks good to me, thank you!

**Comment by hughfdjackson** [comment]
If this change is intended for use with 0.16 is in master, should we update the `elm-version` in `elm-package.json`? 

I'm failing to get master to compile on the latest version available via http://elm-lang.org/install, which I believe to be 0.15.1.

**Comment by laszlopandy** [comment]
Yes. This is true. But I believed that we don't need to bump until we
publish a new version of core to the package repository.

**Comment by hughfdjackson** [comment]
:) From the perspective of someone looking to submit a first PR, it would be time-saving if the `elm-package.json` file reflected the current requirements of master.  Took a little head-scratching to realise I was using the wrong compiler version. 

I'm happy to bump the version requirements in a PR if you and @evancz (et. al.) are on board with that.

**Comment by laszlopandy** [comment]
Makes sense to me.

**Pull request merged**
