### PR TITLE
Document potential gotcha. Fail is when a 'value', not 'key', can't be decoded

### PR DESCRIPTION
**Pull request by simonh1000**

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Maybe the same information should be added to the documentation of the dict-function as well?

**Comment by jvoigtlaender** [comment]
@simonh1000, why close this?

**Comment by simonh1000** [comment]
Because I got totally confused with Git/Github!
Need to start again from scratch

**Comment by jvoigtlaender** [comment]
Isn't just reopening this pull request here an option? (There's a button with that functionality at the bottom.)

**Pull request merged**
