### PR TITLE
fix result of String.toFloat "." (#336)

### PR DESCRIPTION
**Pull request by Pisys**
which is now a Err instead of Ok NaN.
Also added tests for String conversion.

### CODE REVIEW

**Comment by evancz** [comment]
I wonder if this is how we should be implementing this in the first place. Maybe it would be better to use a regex like `[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?` or to just put `parseFloat` in a `try` block and trust that it'll do the right thing?

I also wonder why `parseFloat('.') == NaN` in JavaScript. Can you try to find out why that is true?

**Comment by Pisys** [comment]
parseFloat is less strict than the current implementation. It allows whitespaces, exponents, and only demands a prefix of the input string to be a float. Since "." is not a Float parseFloat returns NaN!

However, parseFloat can also parse "Infinity", which is a Number in JavaScript but not in Elm! So I discourage the mere wrapping of parseFloat until there is a explicit Infinity thing in Elm, such as `x = Infinity` (instead of `x = 0/0`).

**Comment by jvoigtlaender** [comment]
How is this pull request related to https://github.com/elm-lang/core/pull/342?

**Comment by jvoigtlaender** [comment]
I'm closing this for now, since it appears to be overridden by https://github.com/elm-lang/core/pull/342. Please re-open with comment if you disagree.

**Pull request closed without merging**
