### PR TITLE
A quick fix on https://github.com/elm-lang/core/issues/618

### PR DESCRIPTION
**Pull request by ivanceras**
Making sure `decoder` and `result` is not `undefined`

---
This change is [Reviewable](https://reviewable.io/reviews/elm-lang/core/619)

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
This is not how this issue will be fixed.

**Comment by jvoigtlaender** [comment]
Well, let's leave that decision to Evan, actually. Maybe he wants to fix the Json decoder special case that way for the moment. But the general solution is of course to fix the compiler issue.

**Comment by ivanceras** [comment]
I should have used the word `workaround`. This is just a workaround, which solves the issue while a proper fix has not yet landed. This lets me continue work on my projects.

**Comment by jvoigtlaender** [comment]
Yes, I realize it's just a stop-gap measure for a specific case. Which is why I don't believe Evan is going to want to merge it into core. 

As I commented in the issue itself, there are existing workarounds, without changing core. Mainly using the lazy-function from package elm-lang/lazy.

**Comment by evancz** [comment]
It looks like this just makes the crash happen later. It will still definitely happen though as far as I can tell. Better to actually fix things.

**Pull request closed without merging**
