### PR TITLE
Fix semantics of fpsWhen.

### LINKED ISSUE #139: Semantics of `fpsWhen` is quite off.
So, in https://github.com/jvoigtlaender/core/commit/274cd7eb9a05c1b32dab563a871c557097bc3392 I had been trying (as part of the effort to make `timestamp` work in a consistent manner over all signals) to refactor `fpsWhen` while preserving its semantics. I failed in that, which luckily was caught by @jwmerrill, and fixed in https://github.com/elm-lang/core/commit/6a36cd7244420b1a4cde6af870da76bb2b447361. Throughout all this, I hadn't been checking what the semantics of `fpsWhen` was exactly, only trying to preserve it. Have now looked into the semantics of `fpsWhen` and found serious problems, I think.

Let's consider a signal `isOn` with the following behavior:
* initial value `False`
* at 0.5 seconds, has a `True` event
* at 2.0 seconds, has a `False` event
* at 3.5 seconds, has a `True` event
* at 4.0 seconds, has a `False` event
* no further events

For example,
```elm
isOn = flip member [1,7] <~ keepIf (flip member [1,4,7,8]) 0 (foldp (\_ c -> c+1) 0 (every 500))
```

Let's now consider the signal obtained by `fpsWhen 1 isOn`. Surprisingly, it shows the following behavior (since at least Elm-0.13):
* at 0.5 seconds, has an event with value 0
* at around 1.5 seconds, has an event with value 0
* at 2.0 seconds, has an event with value 0
* at around 2.5 seconds, has an event with value around 1000
* at 3.5 seconds, has an event with (same) value around 1000
* at 4.0 seconds, has an event with (same) value around 1000
* at around 4.5 seconds, has an event with value 0
* no further events

One way to check these claims is to run
```elm
main = asText << snd <~ foldp (\(t',d) (t,l) -> (t',(t'-t,d)::l)) (0,[]) (timestamp (fpsWhen 1 isOn))
```
(for example with different language versions at http://share-elm.com)

Many of the values we see appearing are dubious (for example, `isOn` was `True` only for 2 seconds overall, and yet we see three time deltas of 1 second each). Also, the events at 2.5 and 4.5 seconds shouldn't be happening at all. It turns out that the `clearTimeout` in the implementation of `fpsWhen` has no effect whatsoever. PR https://github.com/elm-lang/core/pull/138 fixes that specific "bogus events" aspect. However, even after that fix, the semantics of `fpsWhen` is still off. For the above situation it now behaves as follows:
* at 0.5 seconds, has an event with value 0
* at around 1.5 seconds, has an event with value 0
* at 2.0 seconds, has an event with value 0
* at 3.5 seconds, has an event with value 0
* at 4.0 seconds, has an event with value 0
* no further events

Now the bogus events at 2.5 and 4.5 seconds are gone, but all other events show value 0, even though the `isOn` signal has been `True` for 2 seconds, of which 1.5 seconds were consecutively, so certainly should have shown some non-0 time value passing, given that our granularity was "1 frame per second".

### PR DESCRIPTION
**Pull request by jwmerrill**
fixes #139
alternative to #141

Semantics:

1. fpsWhen fires whenever isOn changes, or its internal setTimeout fires
2. Its value is a timedelta, which is 0 when isOn changes from false to true,
or is the time elapsed since the last event otherwise. As a corrolary, summing
deltas gives exactly the time between when isOn transitioned from false to
true, and when it transitioned from true to false.

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Looks okay also, except:

When the `isOn` signal passed to `fpsWhen` is initially `False`, you call `clearTimeout` on the uninitialized `timeoutId` variable.

**Comment by jwmerrill** [comment]
> When the isOn signal passed to fpsWhen is initially False, you call clearTimeout on the uninitialized timeoutId variable.

I could buy an argument that this is bad style, but it doesn't cause any problems.

Per [the spec](https://html.spec.whatwg.org/multipage/webappapis.html#dom-windowtimers-cleartimeout)

> If handle does not identify an entry in the list of active timers of the WindowTimers object on which the method was invoked, the method does nothing.

and it seems to be implemented this way in all the major browsers.

**Comment by jvoigtlaender** [comment]
Well, okay. But wouldn't adding an `if (wasOn)` on line https://github.com/jwmerrill/core/blob/alternate-fpswhen-fix/src/Native/Time.js#L41 still be nicer than relying on the fact that `clearTimeout(undefined)` should do no harm?

**Comment by jvoigtlaender** [comment]
BTW, it might also be a bit nicer (same in my alternative PR), to have `var wasOn = false;` in this line: https://github.com/jwmerrill/core/blob/alternate-fpswhen-fix/src/Native/Time.js#L29. It would be more obvious then that if the initial value of the `isOn` signal is `True`, it gets "turned on" at initialization time of the program. (Semantics is unchanged, since in the situation where the proposed change has an impact, `timestamp - previousTime` in line https://github.com/jwmerrill/core/blob/alternate-fpswhen-fix/src/Native/Time.js#L46 will be `0` anyway.)

**Comment by jwmerrill** [comment]
> wouldn't adding an if (wasOn) on line https://github.com/jwmerrill/core/blob/alternate-fpswhen-fix/src/Native/Time.js#L41 still be nicer than relying on the fact that clearTimeout(undefined) should do no harm?

Yes, done.

**Comment by jvoigtlaender** [comment]
I've closed https://github.com/elm-lang/core/pull/141 in favour of this PR here.

**Comment by jwmerrill** [comment]
> it might also be a bit nicer (same in my alternative PR), to have var wasOn = false

Agreed--makes the semantics for the first value clearer. Done.

**Comment by jwmerrill** [comment]
Incidentally, if I was implementing this in Elm instead of JS, I think it would be better to use `Signal.merge` instead of `Signal.map2` to create the main input here: https://github.com/elm-lang/core/blob/b1891ed42cd083761195abafaa4e287333ecf04d/src/Native/Time.js#L27

The merged type could be something like

```elm
type Action = Toggle Bool | Tick
```

and then inside update we could match on the input type.

But in JS, it seems like this would make things less clear instead of more.

**Comment by jvoigtlaender** [comment]
This whole PR fixes the semantics of `fpsWhen` in "normal execution mode". In the presence of hot-swapping, the signal still has problems. Hot-swapping modules in general only works reliably if every state relevant for a signal is part of a signal's `.value` (might be the same signal or a signal from which it is derived), because such values are the only kind of information that is copied over from the old signal graph to the new signal graph on hot-swapping. Here now the `wasOn`, `previousTime` and `timeoutId` are such relevant state, but not part of any signal's `.value`. That problem was not actually introduced here, or by my earlier changes in https://github.com/elm-lang/core/pull/76 or refactorings since then. Looking back through the history of the `Time.js` file, it has existed for a long while, since the various variables like `wasOn`, `prev`,  `timeoutID` were not attached to a signal then either.

Likely solution: introduce a `foldp` somehow to manage handling of `wasOn`, `previousTime`, `timeoutId` (should be easier now than in the earlier version, where the main update, then called `startStopTimer`, was mapped over two signals).

**Comment by evancz** [comment]
Is it possible to figure out how to write some tests for this? @laszlopandy is concerned that the semantics are easy to change accidentally, and it's easy for people to rely on certain oddities or be impacted by changes.

**Comment by evancz** [comment]
I don't think we need a general purpose signal testing framework, we just need a way to verify that the core signal functions work as we expect. It seems that this can be done entirely in JS by just dealing with native modules.

**Comment by jvoigtlaender** [comment]
I'm afraid I don't have anything to contribute to a principled way of testing signal implementations. I've been doing this by hand using Elm code like shown in #139.

About the specific case of `fpsWhen`:
* I've now written a version that packages all state in a signal, which should make hotswapping work okay: #143.
* The semantics certainly changes here from what it was in Elm since at least 0.13. But that semantics was clearly in direct and strong conflict with what the documentation of `fpsWhen` is saying. Events that shouldn't be there. Time deltas not summing up to what they should. See the first example in #139. So if in this case people have been relying on the oddities, their code should really be updated. I don't see a point of even trying to be backwards compatible here.

**Comment by jwmerrill** [comment]
Closing in favor of #143

**Pull request closed without merging**
