### PR TITLE
Improve collage documentation

### PR DESCRIPTION
**Pull request by jvoigtlaender**
Motivation for the change is here: https://github.com/elm-lang/core/pull/392#issuecomment-138097389.

### CODE REVIEW

**Comment by eeue56** [comment]
+1

**Comment by evancz** [comment]
It seems kind of tortured to me. How about this?

> Create a collage with certain dimensions and content. It takes a width and height argument to specify dimensions, and then a list of 2D forms to describe the content.
>
> Unlike with Elements, these 2D forms can be moved and rotated however you like. The forms are drawn in the order of the list, i.e., `collage w h [a, b]` will draw `b` on top of `a`.

**Comment by eeue56** [comment]
Better than the current and the new proposal too, +1

**Comment by jvoigtlaender** [comment]
I have changed the comment in an additional commit here, using Evan's suggestion.

**Comment by evancz** [comment]
Great, thank you!

**Pull request merged**
