### PR TITLE
fix incorrect example in documentation of Dict.get

### PR DESCRIPTION
**Pull request by joelgrus**

### CODE REVIEW

**Comment by ajhager** [comment]
:+1: LGTM

**Comment by evancz** [comment]
Thank you @joelgrus! And thanks @ajhager for the ping, seems like I am having trouble monitoring new issues through email notifications. Need to develop a more robust technique.

**Comment by ajhager** [comment]
I was going to go through and mark all PRs that are obviously correct, but I didn't want to spam your inbox.

**Comment by evancz** [comment]
That would be very extremely helpful and appreciated!

**Pull request merged**
