### PR TITLE
Reword millisecond docs to give example of usage

### PR DESCRIPTION
**Pull request by eeue56**
As per #373, makes millisecond docs simpler to understand

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
I don't really like the talk of "variable" here (in the new documentation comment). Does the `core` documentation use language like "variable" elsewhere?

Generally, wouldn't a much easier fix to the problematic aspect of the documentation you point out be to simply replace `(500 * milliseconds)` by `(500 * millisecond)`? Why is the rest of the rewording necessary from your perspective?

**Comment by eeue56** [comment]
I've removed the word variable now - I agree it didn't feel right there.

That would be an easier fix, but a less clear fix I feel. I wanted an explicit code example that people could use right away, rather an example just in the brackets, which doesn't seem as obvious that it's meant to be code. Adding `halfSecond = 500 * millisecond` makes it more explicit and obvious than `(500 * millisecond)` in the middle of a sentence, basically.

**Comment by eeue56** [comment]
Though I could just change it to remove the `s` if you think that's clear enough.

**Comment by jvoigtlaender** [comment]
I actually think just removing the plural `s` would be enough.

**Comment by jvoigtlaender** [comment]
That it's code, should be clear from type-setting on the docs page.

**Comment by eeue56** [comment]
Okay - changed it so it's now just the 's' removal, and got rid of the previous commits I made too.

**Pull request merged**
