### PR TITLE
Help explain purpose of !

### PR DESCRIPTION
**Pull request by willnwhite**

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
There is #678.

**Comment by jvoigtlaender** [comment]
@willnwhite, any comment on the redundancy of your PR due to the older one I linked to?

**Comment by evancz** [comment]
@jvoigtlaender, curating issues and PRs is better done by maintainers, not folks who open stuff. I think the other one is too verbose, and I think this one may need some extra info. The right move is probably to just remove `(!)` entirely.

I don't know if you saw [this talk](https://www.youtube.com/watch?v=DSjbTC-hvqQ&list=PLglJM3BYAMPH2zuz1nbKHQyeawE4SN0Cd&index=1) I did recently, but one of the points I try to make is that it's fine to let stuff like this sit for a while. It looks like a PR, but it's really a report that `(!)` is kind of confusing.

**Comment by jvoigtlaender** [comment]
Particularly as a report rather than PR it seems a duplicate of that other one. But good to know how you want to handle this.

**Comment by willnwhite** [comment]
I've read #678 and added some more info to this PR. I hope this could help before any removal of `(!)` occurs.

**Comment by bukzor** [comment]
+1 to remove (!)

**Comment by Pilatch** [comment]
@evancz I hear that `!` is confusing, and that's a reason to remove it, but until it's removed, it would be a shame to not clear up that confusion for newcomers to the language.

**Comment by evancz** [comment]
The current plan is to drop this operator for the next release. If that does not happen, I will add it back with documentation.

**Pull request closed without merging**
