### PR TITLE
Trivial (hopefully) fixes to docs

### PR DESCRIPTION
**Pull request by mgold**
This PR is meant to be very easy to merge. If there's something you don't like, let me know and I'll back it out. I added a few clarifying notes that shouldn't be too controversial and removed a reference to the nonexistent `(?)` operator. Dict and Set equality is unreliable as a point of fact and we should document it.

````elm
import Set as S
import Text (asText)

main = asText <| S.fromList [1,2] == S.fromList [2,1]
````
Again, let me know if any particular change is troublesome. Thanks.

### CODE REVIEW

**Comment by evancz** [comment]
I didn't really like the Signal changes, and I didn't know how to resolve that. That's why I did not merge earlier. Otherwise it is good.

**Comment by mgold** [comment]
I assume you mean the docs changes? Fine, reverted. If there's anything else, please just say so. Or merge and then fix yourself.

**Comment by evancz** [comment]
Cool, thank you!

**Comment by evancz** [comment]
As of yesterday, there are [some guidelines](https://github.com/elm-lang/core/blob/master/CONTRIBUTING.md) for contributions on this repo. In the future, please make PRs minimal. If it can reasonably be split up, it should be split up.

**Pull request merged**
