### PR TITLE
Update tests for Elm 0.16

### PR DESCRIPTION
**Pull request by deadfoxygrandpa**
I don't think the core library tests need to depend on building Elm Platform from source. The build has been erroring out on travis for quite some time. I'm going to try updating everything relevant to get the tests working again.

### CODE REVIEW

**Comment by deadfoxygrandpa** [comment]
Crap, I didn't check the open PRs and ended up redoing basically everything in https://github.com/elm-lang/core/pull/446, but it seems to be working now at least.

**Comment by deadfoxygrandpa** [comment]
I don't want to push too hard, but it would be nice to get this PR accepted. Tests have been broken for a while and this will enable them to check all the other PRs and commits again.

**Comment by jvoigtlaender** [comment]
@evancz, you may not have seen this. It brings the tests in this repository to a state where we have useful monitoring again.

**Comment by jonathanperret** [comment]
I hate to comment just to say :+1: but this does look like it would be very useful. I just cloned this repo hoping to contribute and was surprised to discover I couldn't run the tests.

**Comment by evancz** [comment]
@deadfoxygrandpa, I do not have notifications on for a lot of repositories. The volume of messages is too high, so instead of always responding to whatever is going on, I periodically do a more comprehensive review of repos. If I did not do this, I feel I would make no real progress anymore.

In any case, I got a notification on this because I was cc'd maybe in a deleted comment. This is nice, thank you!

**Comment by jonathanperret** [comment]
The error reported by Travis is weird:

```
Linking elm-stuff/packages/elm-lang/core/3.0.0 to /home/travis/build/elm-lang/core
Problem in dependency elm-lang/core 3.0.0
The elm-package.json constraints of 'elm-lang/core' are probably
letting too much stuff through. Definitely open an issue on the relevant github
repo to get this fixed and save other people from this pain.
In the meantime, take a look through the direct dependencies of the broken
package and see if any of them have had releases recently. If you find the new
thing that is causing problems, you can artificially constrain things by adding
some extra constraints to your elm-package.json as a stopgap measure.
Detected errors in 1 module.
```

I don't have this problem locally, nor even in Travis builds of my fork: https://travis-ci.org/jonathanperret/elm-core/builds/111891215

One difference is that Travis uses its container-based infrastructure (https://docs.travis-ci.com/user/workers/container-based-infrastructure/) for builds of my fork, because it is the default for repos recognized by Travis after 2015-01-01.

I've prepared PR #509 that forces container-based builds for this repo. The resulting build passes: https://travis-ci.org/elm-lang/core/builds/111895888. This does not explain the problem above, but at least merging #509 should allow tests to be green again on https://github.com/elm-lang/core .

**Pull request merged**
